modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_forge},)"
license = "MIT"

[[mods]]
modId = "abadoned_greatwork"
version = "${version}"
displayName = "Abadoned Greatwork"
logoFile = "assets/abadoned_greatwork/icon.png"
authors = "xm1221"
description = "Abadoned Greatwork addon for Hex Casting"

[[dependencies.abadoned_greatwork]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abadoned_greatwork]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abadoned_greatwork]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abadoned_greatwork]]
modId = "cloth_config"
mandatory = true
versionRange = "[${versions.cloth_config},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abadoned_greatwork]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting},)"
ordering = "NONE"
side = "BOTH"
